### ISSUE TITLE
Fault-tolerant testing

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/smart-pointers#29]
The current test suite has one main driver program, which has the following consequences:

* A compile-time error on one test means no tests can be compiled and run and
* A runtime error in one test means no subsequent tests can run.

To circumvent the above problems, it would be nice to have multiple drivers.  Options include

1. One driver for compiler tests and a separate one for usage tests,
2. One driver for each check function in the test suite, or
3. Something between these two extremes, e.g., a separate driver for each of the currently problematic check functions.

**Comment by everythingfunctional** [comment]
I'll have to think on this one a bit. I'm not sure separate drivers solves your compile-time error problems. Need to do some testing of fpm to be able to tell.

**Comment by rouson** [comment]
@everythingfunctional it suddenly occurs to me that the above compile-time issue might provide another motivation for parallelizing `fpm`: with parallel builds, a compile-time failure on one branch of the DAG wouldn't prevent compilation from continuing on another branch.  It still might not be a big enough deal to be worth pursuing though.

**Comment by wyphan** [comment]
@rouson Parallelizing `fpm`? Now that's interesting. Are you planning to use coarrays, MPI, or OpenMP? Or a combination of those three?

IMHO using coarrays might heighten the entry barrier to fpm due to classic Flang (and its derivatives `nvfortran`, AOCC `flang`, and `armflang`) until LLVM lowering for LLVM Flang is finally done... Unless someone is dedicated enough, say, to get Caffeine working on these compilers.

**Comment by rouson** [comment]
The test suite now has separate compiler tests and usage tests -- both executed by the same driver, but with one of the tests split off into example/test-support and run by `execute_command_line`.  The full test suite passes with the NAG compiler, which bolsters my confidence the failing tests with other compilers are compiler bugs.  I think we don't necessarily need separate drivers now.  And in retrospect, I probably could have just grouped the files into subdirectories and created separate drivers for each subdirectory.

**Comment by rouson** [comment]
@wyphan the plan was to use [FEATS] to parallelize `fpm`.  We've had a couple of close calls where it appeared funding to work on that might materials but no luck yet.

[FEATS]: https://github.com/sourceryinstitute/feats
